### ISSUE TITLE
Linux dependance

### ISSUE THREAD

**Issue by iplayfast** [PeachyPrinter/peachyprinter#1]
for Linux Mint (which is a ubuntu/debian type of distro) you need
python-virtualenv

also kivi has added some dependencies 
sudo apt-get install libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0

which I installed when I got the following (didn't fix):

```
[INFO   ] [Text        ] Provider: pil(['text_pygame'] ignored)
INFO:kivy:[Text        ] Provider: pil(['text_pygame'] ignored)
[CRITICAL] [App         ] Unable to get a Window, abort.
CRITICAL:kivy:[App         ] Unable to get a Window, abort.
 Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
WARNING:kivy:stderr: Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
[INFO   ] [Audio       ] Providers:  (audio_pygame, audio_pygst, audio_ffpyplayer ignored)
INFO:kivy:[Audio       ] Providers:  (audio_pygame, audio_pygst, audio_ffpyplayer ignored)
[CRITICAL] [App         ] Unable to get a Window, abort.
CRITICAL:kivy:[App         ] Unable to get a Window, abort.
 Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
WARNING:kivy:stderr: Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
[CRITICAL] [App         ] Unable to get a Window, abort.
CRITICAL:kivy:[App         ] Unable to get a Window, abort.
 Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
WARNING:kivy:stderr: Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
[CRITICAL] [App         ] Unable to get a Window, abort.
CRITICAL:kivy:[App         ] Unable to get a Window, abort.
 Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
WARNING:kivy:stderr: Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
[CRITICAL] [App         ] Unable to get a Window, abort.
CRITICAL:kivy:[App         ] Unable to get a Window, abort.
 Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
WARNING:kivy:stderr: Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
[INFO   ] [Specifed Language Locale] en_CA
INFO:kivy:[Specifed Language Locale] en_CA
 Traceback (most recent call last):
WARNING:kivy:stderr: Traceback (most recent call last):
   File "src/main.py", line 82, in <module>
WARNING:kivy:stderr:   File "src/main.py", line 82, in <module>
     PeachyPrinter(api, language=args.lang).run()
WARNING:kivy:stderr:     PeachyPrinter(api, language=args.lang).run()
   File "/home/chris/github/peachyprinter/src/gui.py", line 171, in __init__
WARNING:kivy:stderr:   File "/home/chris/github/peachyprinter/src/gui.py", line 171, in __init__
     Window.size = (1000, 700)
WARNING:kivy:stderr:     Window.size = (1000, 700)
 AttributeError: 'NoneType' object has no attribute 'size'
WARNING:kivy:stderr: AttributeError: 'NoneType' object has no attribute 'size'
```

**Comment by iplayfast** [comment]
apt-get install python-kivy seems to have fixed the problems. Now I'm getting a page, that says no printer found.

**Comment by jtownley** [comment]
Hi, 
I have never used Mint. Did you run the build script like
"./build.sh -i -j" that should install the dependencies required. If Mint uses different dependencies names the build will fail and the rules to allow the printer to connect will not be added.

If you are feeling up to it you can edit the dependencies at the top of the build .sh file, then run the script again.

Also I am not sure what version of kivy ships with Mint but we expect 1.9.1 it should install via the build script once the dependencies install correctly.

Also remember to run with the run.sh script that should be created on a successfully built project.
